# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
# To update look at what fabric template generator gives (https://fabricmc.net/develop/template/)
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.me.coresmodule
archives_base_name=coresmodule

# Dependencies
fabric_api_version=0.154.2+26.1.2

# Resourceful Config
rconfig_version=26.1:4.0.1

# Elementa
elementaVersion=714
uc_version=505

modmenu_version=18.0.0-alpha.8

json_version=20250517

JDA_v=6.4.1